# 03 - Base Line Model

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/midfielder_clusters.csv")

for cluster in sorted(df["cluster"].unique()):
    print(f"\n{'='*40}")
    print(f"CLUSTER {cluster}")
    print(f"{'='*40}")

    players = df[df["cluster"] == cluster]

    display(
        players[
            [
                "player_name",
                "minutes_played",
                "scoring.expected_goals_per90",
                "scoring.expected_assists_per90",
                "defending.tackles_per90",
                "defending.interceptions_per90"
            ]
        ].sort_values(
            "scoring.expected_assists_per90",
            ascending=False
        ).head(10)
    )

========================================
CLUSTER 0
========================================

,player_name,minutes_played,scoring.expected_goals_per90,scoring.expected_assists_per90,defending.tackles_per90,defending.interceptions_per90
58,Rayan Cherki,1794,0.197157,0.412876,1.304348,0.351171
60,Bruno Fernandes,3066,0.303229,0.378082,1.585127,0.587084
12,David Brooks,1220,0.449262,0.235328,1.401639,0.295082
56,Enzo Fernández,3121,0.311439,0.199840,1.528356,0.605575
57,Phil Foden,2107,0.251590,0.194352,1.452302,0.384433
53,Florian Wirtz,2388,0.256658,0.186935,1.281407,0.414573
13,Justin Kluivert,951,0.211041,0.151420,0.946372,0.378549
2,Eberechi Eze,1900,0.229737,0.129789,0.900000,0.521053
5,Mikel Merino,1035,0.284348,0.122609,2.260870,0.869565
21,Jack Hinshelwood,1750,0.243771,0.115200,0.977143,0.257143

========================================
CLUSTER 1
========================================

,player_name,minutes_played,scoring.expected_goals_per90,scoring.expected_assists_per90,defending.tackles_per90,defending.interceptions_per90
31,Adam Wharton,2562,0.051639,0.250117,2.459016,0.948478
17,Mathias Jensen,2277,0.085375,0.229644,1.620553,0.830040
3,Martin Ødegaard,1370,0.078175,0.229270,1.248175,0.459854
18,Mikkel Damsgaard,2078,0.108277,0.226083,2.468720,1.082772
22,Pascal Groß,1636,0.076467,0.218949,1.595355,0.660147
1,Declan Rice,3099,0.088577,0.194288,2.032914,1.074540
86,Xavi Simons,1769,0.149576,0.187224,1.729791,0.763143
52,Dominik Szoboszlai,3233,0.129168,0.180668,1.558924,0.835138
38,Kiernan Dewsbury-Hall,2635,0.142087,0.176926,1.776091,0.409867
0,Bruno Guimarães,2455,0.196864,0.174501,2.272912,0.549898

========================================
CLUSTER 2
========================================

,player_name,minutes_played,scoring.expected_goals_per90,scoring.expected_assists_per90,defending.tackles_per90,defending.interceptions_per90
50,Sean Longstaff,1046,0.104111,0.158317,3.269598,1.032505
65,Youri Tielemans,1862,0.054619,0.154672,2.803437,0.870032
37,James Garner,3414,0.051406,0.149736,3.163445,1.555360
19,Vitaly Janelt,1449,0.054037,0.136646,1.677019,1.863354
55,Elliot Anderson,3334,0.075315,0.123635,2.807439,1.106779
46,Ao Tanaka,1326,0.103846,0.095701,1.832579,1.425339
83,Mateus Fernandes,3024,0.056548,0.083929,3.065476,1.041667
25,Josh Cullen,1519,0.051547,0.077024,1.836735,1.303489
72,Ibrahim Sangaré,2080,0.047163,0.074423,2.552885,1.081731
29,Moisés Caicedo,2802,0.044004,0.073233,2.794433,1.895075